### PR TITLE
Remake of Documentation Framework. Moved from Jekyll to Docusaurus. Github Actions to publish on pages included.

### PR DESCRIPTION
**Pull request by voxelin**
Remake of Documentation Framework. Moved from Jekyll to Docusaurus. Github Actions to publish on pages included.

**PLEASE, MERGE PULL REQUEST USING REBASE TO PREVENT ERRORS**

### CODE REVIEW

**Comment by kbdharun** [comment]
Nice, I will take a close look at it soon.

**Review by kbdharun — CHANGES_REQUESTED** [review]
Why are the Tamil (ta) pages I added removed and not moved to the `i18n` folder? **Before proceeding further, I would like to know the supported locales of docusaurus.**

If it doesn't support all locales, I would strongly oppose the change as we could just use a language switcher with Jekyll in docs. (But the limitation, being the page doesn't look modern)

@mirkobrombin Don't merge this before this conversation is resolved.

**Comment by kbdharun** [comment]
I noticed in their docs they have suggested Crowdin for managing translations does it mean that every language in Crowdin is supported?

**Comment by delight-aug** [comment]
Is there any prior discussion for this change? It's very out of the blue for me

**Comment by delight-aug** [comment]
I skimmed through the changes and I see that you have included quite a few improvements in this PR. The issue is, I suspect none of them were previously discussed. This doesn't mean we aren't willing to merge them, but it doesn't mean the opposite either.

Let's do it like this — for each change, open an issue describing the problem you're trying to solve and in what way you're solving it. After we evaluate each issue, if we indeed need the change, we will ask you to submit a smaller PR that only solves that issue.

If you're fine with this approach, please close this PR for now. But do not delete your branch, it'll be useful later.

For future reference, please refrain from submitting big unexpected PRs, I can guarantee you they will never be merged — maintainers do not like surprises.

**Pull request closed without merging**
