### PR TITLE
added entry and first draft of the pt_br translation

### PR DESCRIPTION
**Pull request by Vilianexe**
new file:   index.pt_br.md

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Is this still a draft?

**Comment by Vilianexe** [comment]
> Is this still a draft?

yeah. i'm gonna finish translating today

**Comment by Vilianexe** [comment]
Now is finished, i tried my best, but it need to be reviewed by other pt_br translators

**Comment by kbdharun** [comment]
Thanks for your contribution.

**Pull request merged**
