### PR TITLE
Add some German translation

### PR DESCRIPTION
**Pull request by gregorni**
German translations for the apx manpage, almost configuration and almost layers

More german translations to come:
- [ ] index
- [x] abroot index
- [x] abroot manpage
- [x] ~~almost index~~
- [x] ~~almost manpage~~
- [ ] vso index
- [ ] vso manpage

### CODE REVIEW

**Comment by gregorni** [comment]
Should I also translate the documentation of almost, or is that just a waist of time? Because I understand it's replaced by ABRoot.

**Comment by kbdharun** [comment]
> Should I also translate the documentation of almost, or is that just a waist of time? Because I understand it's replaced by ABRoot.

I would suggest skipping it.

**Comment by gregorni** [comment]
> You can skip the almost directory altogether.

Should I remove the two files I uploaded there?

**Comment by kbdharun** [comment]
> > You can skip the almost directory altogether.
> 
> Should I remove the two files I uploaded there?

I think you can leave it as it is I guess.

**Comment by gregorni** [comment]
What does the `vso rotate-tasks` command do?

**Comment by kbdharun** [comment]
> What does the `vso rotate-tasks` command do?

It rotates execution of the task. For example something like shuffle in music players but for scheduled tasks. This will allow you to randomly execute a task.

**Comment by gregorni** [comment]
> randomly execute a task

Really randomly?

**Comment by gregorni** [comment]
I probably won't be working on this translation in the near future, so I think you should merge this already. I'll work on the `index` & `vso` sometime else. Also, there's #77 for the `apx index`, which is shorter and more up-to-date, so you might want to replace my version with theirs.

**Review by kbdharun — APPROVED** [review]

**Pull request merged**
